CREATE DATABASE BLOG;

CREATE TYPE USER_TYPE AS ENUM('1','2');

CREATE TABLE BUSER (
USER_ID SERIAL PRIMARY KEY,
EMAIL VARCHAR(50) NOT NULL UNIQUE,
PASSWORD VARCHAR(20) NOT NULL,
PROFILE USER_TYPE DEFAULT '2'
);

CREATE TYPE POST_STATUS AS ENUM('1','2','3');

CREATE TABLE POST(
POST_ID SERIAL PRIMARY KEY,
TITLE VARCHAR(150) NOT NULL,
CONTENT TEXT NOT NULL,
TAGS VARCHAR(150),
STATUS POST_STATUS DEFAULT '1',
CREATE_TIME TIMESTAMP,
UPDATE_TIME TIMESTAMP,
USER_ID INT NOT NULL,
CONSTRAINT FK_UID 
FOREIGN KEY(USER_ID) 
REFERENCES BUSER(USER_ID)
);

CREATE TYPE COMMENT_STATUS AS ENUM('1','2');

CREATE TABLE COMMENT(
COMMENT_ID SERIAL PRIMARY KEY,
AUTHOR VARCHAR(40) NOT NULL,
CONTENT VARCHAR(100),
STATUS COMMENT_STATUS DEFAULT '1',
CREATE_TIME TIMESTAMP,
EMAIL VARCHAR(30),
POST_ID INT NOT NULL,
CONSTRAINT FK_PID
FOREIGN KEY(POST_ID)
REFERENCES POST(POST_ID)
);